### ISSUE TITLE
[Feature Request]  Persistent Notifications

### ISSUE THREAD

**Issue by esmoak** [nproth/pin#1]
It would be nice if there was a rudimentary settings menu, perhaps when long pressing on the pin icon, where we could choose an option to have persistent notifications so that they can't be swiped away without being marked as done.

Another setting that could be added in there would be an option to see pins that were marked as complete.

**Comment by nproth** [comment]
Thank you very much for your feedback.

At the moment marking a note as 'done' will automatically delete it. Maybe a log that shows deleted and currently hidden pins could be implemented, I will certainly look into this.

I would rather refrain from adding a settings page because I want to keep the app as simple as possible. But I will consider making the notifications persistent by default and I will add functionality to show all hidden pins (probably by long pressing the timer button), so that you don't have to wait until a note is shown again in case you accidentally swiped away a notification.

**Comment by esmoak** [comment]
Thank you. This is a terrific app already and I love the simplicity. I really appreciate the work you put into the app.

**Comment by nproth** [comment]
That's nice to hear and motivating, thank you.
The option to make notifications persistent is included in an update which will arrive on f-droid over the next few days.
Also I like the idea of some sort of list-view showing hidden and/or dismissed notes but it seems like a bigger addition to the app. Maybe it could be implemented at some point in the future, I definitely have it on my list.

**Comment by esmoak** [comment]
Awesome update. It came through on F-Droid today.

Thanks again.
