### ISSUE TITLE
Issue + feature request

### ISSUE THREAD

**Issue by nihalanand697** [nproth/pin#14]
Issue : locking the notes from app gets disabled if the list in notification panel is expanded. It is needed to enable it again to implement properly.
Feature request : An option in the notification itself to lock notes, would be great if it is for individual notes. :D

**Comment by nproth** [comment]
Thank you for the bug report. I found that expanding the notification panel works fine but snoozing a pin unlocks all notes. If you have encountered additional bugs please specify your android version.

Unfortunately locking individual notes is not possible because Android handles locked notifications differently. I don't think grouping locked and unlocked pins would work. Locked pins would then be displayed in a different group notification. As a result p!n would have to display two lists of notes in the notification area.

**Comment by nihalanand697** [comment]
Yes you are right about the locking of pins. Sorry didn't notice that.
Personally I don't have any issue with having two different groups in noti. panle. But it depends if the other users want it and mostly that you want it. Thanks anyways for creating such a useful app.

**Comment by nproth** [comment]
I won't implement it in the current version of p!n. But I plan to overhaul the app at some point in the future and I will try to incorporate this feature in one form or another.

**Comment by nproth** [comment]
The bug is now fixed. I'm sorry it took me so long.
