### ISSUE TITLE
Maximum of 8 tasks/notes are dispalyed in notification bar

### ISSUE THREAD

**Issue by geekdima** [nproth/pin#3]
**Expected behaviour:**

Have all notes be available to be scrolled through.

**Actual behaviour:**

Only last 8 notes are present in notifications, older ones appear after newer are removed.

**Hardware and Software:**

* SM-A520F - Samsung Galaxy A5 (2017)
* Android 8.0.0 (Kernel 3.18.14)
* Samsung Experience 9.0
* Nova Launcher

**Remarks:**

Not sure if this is problem on your side, or on Samsung's or even Android. 

P.S. Love how simple your app is, it's amazing. Great job!

----
Example:

![ezgif-4-d4043fed60dc](https://user-images.githubusercontent.com/1625978/55036057-2d433480-5022-11e9-9ee5-e1da4b7005db.gif)

**Comment by nproth** [comment]
Unfortunately this seems to be an Android restriction.
As a workaround (for now) you could hide newer notifications via 'snooze' to access older ones and then long-press the timer-button to show all hidden pins again.

Still there might by a way around this restriction by using one notification with a custom layout, displaying a list of pins, instead of several standard ones. However, this would probably not integrate equally well with android's notification design and handling.

**Comment by geekdima** [comment]
Thank you for your reply. As I thought this wasn't your issue. Keep doing great work!
